name: CMDCooldown
version: '1.1'
main: net.legendahlupa.com.cmdcooldown.CMDCooldown
api-version: '1.17'
description: "Plugin for cooldown commands"
author: LegendaHluPa
commands:
  CommandCooldown:
    aliases:
      - cmdc
      - cc